<a href="https://colab.research.google.com/github/AnnaK8090/CIND-820_Big-Data-Analytics-Project/blob/main/CIND_820_Big_Data_Analytics_Project_BASIC_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np 
import pandas as pd

In [6]:
#Loading csv files
customersDF = pd.read_csv("olist_customers_dataset.csv")
geolocationDF = pd.read_csv("olist_geolocation_dataset.csv")
order_itemsDF = pd.read_csv("olist_order_items_dataset.csv")
order_paymentsDF = pd.read_csv("olist_order_payments_dataset.csv")
order_reviewsDF = pd.read_csv("olist_order_reviews_dataset.csv")
ordersDF = pd.read_csv("olist_orders_dataset.csv")
productsDF = pd.read_csv("olist_products_dataset.csv")
sellersDF = pd.read_csv("olist_sellers_dataset.csv")
product_category_name_translation = pd.read_csv("product_category_name_translation.csv")

In [7]:
#Joining tables into a Master DataFrame:
masterDF = ordersDF.copy()
masterDF = masterDF.merge(customersDF,on='customer_id')
masterDF = masterDF.merge(order_reviewsDF,on='order_id')
masterDF = masterDF.merge(order_paymentsDF,on='order_id')
masterDF = masterDF.merge(order_itemsDF,on='order_id')
masterDF = masterDF.merge(productsDF,on='product_id')
masterDF = masterDF.merge(sellersDF,on='seller_id')
masterDF = masterDF.merge(product_category_name_translation,on='product_category_name')
masterDF.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP,housewares
3,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,2017-08-15 18:29:31,2017-08-15 20:05:16,2017-08-17 15:28:33,2017-08-18 14:44:43,2017-08-28 00:00:00,3a51803cc0d012c3b5dc8b7528cb05f7,3366,...,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP,housewares
4,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,2017-08-02 18:24:47,2017-08-02 18:43:15,2017-08-04 17:35:43,2017-08-07 18:30:01,2017-08-15 00:00:00,ef0996a1a279c26e7ecbd737be23d235,2290,...,268.0,4.0,500.0,19.0,8.0,13.0,9350,maua,SP,housewares

In [14]:
masterDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113210 entries, 0 to 115608
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113210 non-null  object
 1   customer_id                    113210 non-null  object
 2   order_status                   113210 non-null  object
 3   order_purchase_timestamp       113210 non-null  object
 4   order_approved_at              113196 non-null  object
 5   order_delivered_carrier_date   113208 non-null  object
 6   order_delivered_customer_date  113202 non-null  object
 7   order_estimated_delivery_date  113210 non-null  object
 8   customer_unique_id             113210 non-null  object
 9   customer_zip_code_prefix       113210 non-null  int64
 10  customer_city                  113210 non-null  object
 11  customer_state                 113210 non-null  object
 12  review_id                      113210 non-null  object
 13  review_score                   113210 non-null  int64
 14  review_comment_title           13497 non-null   object
 15  review_comment_message         47365 non-null   object
 16  review_creation_date           113210 non-null  object
 17  review_answer_timestamp        113210 non-null  object
 18  payment_sequential             113210 non-null  int64
 19  payment_type                   113210 non-null  object
 20  payment_installments           113210 non-null  int64
 21  payment_value                  113210 non-null  float64
 22  order_item_id                  113210 non-null  int64
 23  product_id                     113210 non-null  object
 24  seller_id                      113210 non-null  object
 25  shipping_limit_date            113210 non-null  object
 26  price                          113210 non-null  float64
 27  freight_value                  113210 non-null  float64
 28  product_category_name          113210 non-null  object
 29  product_name_lenght            113210 non-null  float64
 30  product_description_lenght     113210 non-null  float64
 31  product_photos_qty             113210 non-null  float64
 32  product_weight_g               113209 non-null  float64
 33  product_length_cm              113209 non-null  float64
 34  product_height_cm              113209 non-null  float64
 35  product_width_cm               113209 non-null  float64
 36  seller_zip_code_prefix         113210 non-null  int64
 37  seller_city                    113210 non-null  object
 38  seller_state                   113210 non-null  object
 39  product_category_name_english  113210 non-null  object
dtypes: float64(10), int64(6), object(24)
memory usage: 35.4+ MB

In [8]:
masterDF.shape

(115609, 40)

In [9]:
masterDF=masterDF.drop_duplicates()

In [13]:
#Filtering only Delivered orders:
selected_oder_status = ['delivered'] 
    
masterDF = masterDF.loc[masterDF['order_status'].isin(selected_oder_status)] 
    
masterDF.shape

(113210, 40)

In [18]:
# Order ID is not unique and can have multiple reviews on the same date or different dates, so we aggregate orders by order_id and choose max review score:


masterDF_grouped = masterDF.groupby(['order_id','customer_unique_id','product_id','product_category_name_english']).agg({'review_score':['max']})
masterDF_grouped = masterDF_grouped.reset_index()
masterDF_grouped.head()

,order_id,customer_unique_id,product_id,product_category_name_english,review_score
,,,,,max
0,00010242fe8c5a6d1ba2dd792cb16214,871766c5855e863f6eccc05f988b23cb,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,5
1,00018f77f2f0320c557190d7a144bdd3,eb28e67c4c0b83846050ddfb8a35d051,e5f2d52b802189ee658865ca93d83a8f,pet_shop,4
2,000229ec398224ef6ca0657da4fc703e,3818d81c6709e39d06b2738a8d3a2474,c777355d18b72b67abbeef9df44fd0fd,furniture_decor,5
3,00024acbcdf0a6daa1e931b038114c75,af861d436cfc08b2c2ddefd0ba074622,7634da152a4610f1595efa32f14722fc,perfumery,4
4,00042b26cf59d7ce69dfabb4e55b4fd9,64b576fb70d441e8f1b2d7d446e483c5,ac6c3623068f30de03045865e4e10089,garden_tools,5

In [19]:
masterDF_grouped.shape

(98091, 5)

In [20]:
import progressbar as pb
import random

In [ ]:
#Function to convert dataframe into array 

c_data = pd.DataFrame()
products = []
c_data['order_id'] = 0
for product in pb.progressbar(masterDF_grouped['product_id']):
    if product not in products:
        products.append(product)
        c_data[product] = 0
users = []
for user in pb.progressbar(masterDF_grouped['customer_unique_id']):
    if user not in users:
        users.append(user)
        append_dic = {'order_id':user} 
        for column in c_data.columns:
            if column != 'order_id':
                append_dic[column] = 0
        c_data = c_data.append(pd.DataFrame([append_dic]))
c_data = c_data.set_index('order_id')

N/A% (0 of 98091) |                      | Elapsed Time: 0:00:00 ETA:  --:--:--/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  if __name__ == '__main__':
100% (98091 of 98091) |##################| Elapsed Time: 0:01:32 Time:  0:01:32
  0% (62 of 98091) |              | Elapsed Time: 0:02:49 ETA:  3 days, 5:13:10